replicaCount: 1

image:
  repository: ghcr.io/example/example-fastapi
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources: {}

env:
  APP_NAME: "example-fastapi-service"
  APP_VERSION: "0.1.0"
  LOG_LEVEL: "INFO"

dashboards:
  enabled: true
  label: grafana_dashboard
  labelValue: "1"
